### ISSUE TITLE
Flickr images

### ISSUE THREAD

**Issue by sonnybjs** [wchen342/SketchyGAN#36]
Thanks for your work. My question is about the Flickr images,
Is it possible to run the code without the Flickr images, because I can only find the sketchy database you shared, and I don't know how to get paired Flickr images.

**Comment by sonnybjs** [comment]
and it seems my devices are not been detected.


runfile('D:/UTS/SketchyGAN-master/main_single.py', wdir='D:/UTS/SketchyGAN-master')
Launching new train: 2020-04-16-17-18-10
paired file sketchy num: 125
paired file flickr num: 0
Device mapping:

Iteration starts from: 0
Device mapping:

Traceback (most recent call last):

  File "D:\UTS\SketchyGAN-master\main_single.py", line 185, in <module>
    status, appendix = launch_training(**d_params)

  File "D:\UTS\SketchyGAN-master\main_single.py", line 100, in launch_training
    status = train_module.train(**kwargs)

  File "./src_single\train_single.py", line 115, in train
    small=small, capacity=2 ** 11)

  File "./src_single\input_pipeline.py", line 271, in build_input_queue_paired_mixed
    f_list = _f_list()

  File "./src_single\input_pipeline.py", line 266, in _f_list
    paired_filenames_2, test_mode=False, distance_map=distance_map, img_dim=SIZE[small], data_format=data_format)

  File "./src_single\input_pipeline.py", line 84, in get_paired_input
    paired_filenames, capacity=512, shuffle=shuffle, num_epochs=num_epochs)

  File "D:\Anaconda\lib\site-packages\tensorflow_core\python\util\deprecation.py", line 324, in new_func
    return func(*args, **kwargs)

  File "D:\Anaconda\lib\site-packages\tensorflow_core\python\training\input.py", line 258, in string_input_producer
    raise ValueError(not_null_err)

ValueError: string_input_producer requires a non-null input tensor
